<?php

namespace GestionBundle\Repository;

/**
 * FileCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
