<?php

namespace GestionBundle\Repository;

/**
 * PlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningRepository extends \Doctrine\ORM\EntityRepository
{
   
    
     public function findByUser($user)
        {
            $em = $this->getEntityManager();
            $qb = $em->createQueryBuilder();
            $qb->select('p')
                ->from("GestionBundle:Planning", 'p')
                ->where('p.user = :user')
                ->orwhere('p.userDest = :userDest')
                ->setParameters([
                'user' => $user,
                'userDest' => $user,
            ]);
// ->setParameter('user', '%"'.$user.'"%');
            return $qb->getQuery()->getResult();
        }
}

