<?php

namespace GestionBundle\Repository;

/**
 * PushNotifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushNotifRepository extends \Doctrine\ORM\EntityRepository
{
}
