# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    
     app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
            
            
     app.profile.form.type:
        class: UserBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }
            
#     app.change_password.form.type:
#        class: UserBundle\Form\ChangePasswordFormType
#        tags:
#            - { name: form.type, alias: app_user_change_password }


    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
